#!/usr/bin/env python3
"""Dev-time only: build games/pocket-pairs/sprites-data.js and a preview sheet
from scripts/pairs-art/sprites.json (the Claude Design "Art Direction" export).

Requires Pillow — a DEV-TIME tool only, NOT a project dependency:
    python -m pip install Pillow

Run from the arcade-attic repo root:
    python scripts/build-pairs-sprites.py

Re-run whenever sprites.json changes.
"""
from pathlib import Path
import json

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / "pairs-art" / "sprites.json"
OUT_JS = ROOT / "games" / "pocket-pairs" / "sprites-data.js"
OUT_PNG = ROOT / "games" / "pocket-pairs" / "sprites-preview.png"

SIZE = 32
SCALE = 8
COLS = 4


def expand(sp):
    """Mirror the 16-wide `half` across x, then overlay `extra` rows.
    Matches the expand() in art-direction.dc.html exactly."""
    grid = [["."] * SIZE for _ in range(SIZE)]
    half = sp["half"]
    if len(half) != SIZE:
        raise SystemExit(f"{sp['id']}: half has {len(half)} rows, expected {SIZE}")
    for y, row in enumerate(half):
        for x in range(16):
            c = row[x] if x < len(row) else "."
            if c != ".":
                grid[y][x] = c
                grid[y][SIZE - 1 - x] = c
    for k, row in sp.get("extra", {}).items():
        y = int(k)
        if not (0 <= y < SIZE):
            raise SystemExit(f"{sp['id']}: extra key {k!r} out of range 0..{SIZE - 1}")
        for x in range(SIZE):
            c = row[x] if x < len(row) else "."
            if c and c != ".":
                grid[y][x] = c
    return grid


def build_sprite(sp):
    colors = sp["colors"]                       # dict: letter -> "#rrggbb"
    letters = list(colors.keys())               # insertion order = palette order
    if len(letters) > 15:
        raise SystemExit(f"{sp['id']}: {len(letters)} colours (max 15)")
    index = {ch: i + 1 for i, ch in enumerate(letters)}   # 1-based; 0 = transparent
    palette = [None] + [colors[ch] for ch in letters]
    grid = expand(sp)
    pixels = []
    for y in range(SIZE):
        for x in range(SIZE):
            ch = grid[y][x]
            if ch == ".":
                pixels.append("0")
                continue
            if ch not in index:
                raise SystemExit(f"{sp['id']}: char {ch!r} at {x},{y} not in colors")
            pixels.append("%x" % index[ch])
    return {"w": SIZE, "h": SIZE, "palette": palette, "pixels": "".join(pixels)}


def main():
    data = json.loads(SRC.read_text(encoding="utf8"))
    sprites = {sp["id"]: build_sprite(sp) for sp in data}
    ids = [sp["id"] for sp in data]             # keep design order

    body = ",\n  ".join(f"{sid}: {json.dumps(sprites[sid])}" for sid in ids)
    OUT_JS.write_text(
        "// GENERATED by scripts/build-pairs-sprites.py — do not hand-edit.\n"
        "// 32x32 indexed-colour pixel mascots for Pocket Pairs (16, four families).\n"
        "// Source: scripts/pairs-art/sprites.json (Claude Design art-direction export).\n"
        "export const PAIR_SPRITES = {\n  " + body + ",\n};\n",
        encoding="utf8",
        newline="\n",
    )
    print(f"wrote {OUT_JS.relative_to(ROOT)} ({len(ids)} sprites, {OUT_JS.stat().st_size} bytes)")

    # preview sheet — each sprite on the in-game reveal panel colour (#2b2350)
    cell = SIZE * SCALE
    pad, label_h = 16, 16
    rows_n = (len(ids) + COLS - 1) // COLS
    sheet = Image.new(
        "RGBA",
        (COLS * (cell + pad) + pad, rows_n * (cell + pad + label_h) + pad),
        (23, 18, 43, 255),
    )
    draw = ImageDraw.Draw(sheet)
    for k, sid in enumerate(ids):
        sp = sprites[sid]
        rgb = [None] + [
            tuple(int(h[i:i + 2], 16) for i in (1, 3, 5)) for h in sp["palette"][1:]
        ]
        cx = pad + (k % COLS) * (cell + pad)
        cy = pad + (k // COLS) * (cell + pad + label_h)
        img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
        px = img.load()
        for i, ch in enumerate(sp["pixels"]):
            v = int(ch, 16)
            if v:
                px[i % SIZE, i // SIZE] = rgb[v] + (255,)
        draw.rectangle((cx, cy, cx + cell - 1, cy + cell - 1), fill=(43, 35, 80, 255))
        resized = img.resize((cell, cell), Image.NEAREST)
        sheet.paste(resized, (cx, cy), resized)
        draw.text((cx, cy + cell + 3), sid, fill=(240, 240, 248, 255))
    sheet.save(OUT_PNG)
    print(f"wrote {OUT_PNG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
