#!/usr/bin/env python3
"""Dev-time only: build games/pocket-pairs/sprites-data.js and a preview
sheet from the hand-authored pixel grids in scripts/pairs-art/.

Requires Pillow — a DEV-TIME tool only, NOT a project dependency:
    python -m pip install Pillow

Run from the arcade-attic repo root:
    python scripts/build-pairs-sprites.py

Re-run whenever a grid or the palette changes.
"""
from pathlib import Path
import json

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "scripts" / "pairs-art"
OUT_JS = ROOT / "games" / "pocket-pairs" / "sprites-data.js"
OUT_PNG = ROOT / "games" / "pocket-pairs" / "sprites-preview.png"

SIZE = 32
SCALE = 8
COLS = 4
HEXCHARS = "0123456789abcdef"


def load_palette():
    palette = [None]  # index 0 = transparent
    for line in (ART / "palette.txt").read_text(encoding="utf8").splitlines():
        s = line.strip()
        if not s:
            continue
        if len(s) != 7 or s[0] != "#":
            raise SystemExit(f"palette.txt: bad colour {s!r}")
        palette.append(s)
    if len(palette) - 1 > 15:
        raise SystemExit("palette.txt has more than 15 colours (hex chars only reach 'f')")
    return palette


def load_grid(path, max_index):
    rows = path.read_text(encoding="utf8").splitlines()
    while rows and rows[-1].strip() == "":
        rows.pop()
    if len(rows) != SIZE:
        raise SystemExit(f"{path.name}: expected {SIZE} rows, got {len(rows)}")
    for y, row in enumerate(rows):
        if len(row) != SIZE:
            raise SystemExit(f"{path.name}: row {y + 1} has {len(row)} chars, expected {SIZE}")
        for x, ch in enumerate(row):
            if ch not in HEXCHARS:
                raise SystemExit(f"{path.name}: bad char {ch!r} at col {x + 1}, row {y + 1}")
            if int(ch, 16) > max_index:
                raise SystemExit(
                    f"{path.name}: index {ch} at col {x + 1}, row {y + 1} exceeds palette ({max_index})"
                )
    return "".join(rows)


def main():
    palette = load_palette()
    max_index = len(palette) - 1
    ids = sorted(p.stem for p in ART.glob("*.txt") if p.stem != "palette")
    if not ids:
        raise SystemExit("no *.txt grids in scripts/pairs-art/")

    sprites = {}
    for sid in ids:
        pixels = load_grid(ART / f"{sid}.txt", max_index)
        sprites[sid] = {"w": SIZE, "h": SIZE, "palette": palette, "pixels": pixels}

    body = ",\n  ".join(f"{sid}: {json.dumps(sprites[sid])}" for sid in ids)
    OUT_JS.write_text(
        "// GENERATED by scripts/build-pairs-sprites.py — do not hand-edit.\n"
        "// 32x32 indexed-colour pixel mascots for Pocket Pairs.\n"
        "// Sources: scripts/pairs-art/*.txt  ·  palette: scripts/pairs-art/palette.txt\n"
        "export const PAIR_SPRITES = {\n  " + body + ",\n};\n",
        encoding="utf8",
    )
    print(f"wrote {OUT_JS.relative_to(ROOT)} ({len(ids)} sprites, {OUT_JS.stat().st_size} bytes)")

    rgb = [None] + [tuple(int(h[i:i + 2], 16) for i in (1, 3, 5)) for h in palette[1:]]
    rows_n = (len(ids) + COLS - 1) // COLS
    cell = SIZE * SCALE
    pad, label_h = 16, 16
    sheet = Image.new(
        "RGBA",
        (COLS * (cell + pad) + pad, rows_n * (cell + pad + label_h) + pad),
        (23, 18, 43, 255),
    )
    draw = ImageDraw.Draw(sheet)
    for k, sid in enumerate(ids):
        cx = pad + (k % COLS) * (cell + pad)
        cy = pad + (k // COLS) * (cell + pad + label_h)
        spr = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
        px = spr.load()
        for i, ch in enumerate(sprites[sid]["pixels"]):
            v = int(ch, 16)
            if v:
                px[i % SIZE, i // SIZE] = rgb[v] + (255,)
        sheet.paste(spr.resize((cell, cell), Image.NEAREST), (cx, cy))
        draw.text((cx, cy + cell + 3), sid, fill=(240, 240, 248, 255))
    sheet.save(OUT_PNG)
    print(f"wrote {OUT_PNG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
