#!/usr/bin/env python3
"""One-off: regenerate games/waffle-wednesday/crew-sprites.js from the
world-cup-sweepstake headshots.

Requires Pillow — a DEV-TIME tool only, NOT a project dependency:
    python -m pip install Pillow

Run from the arcade-attic repo root:
    python scripts/pixelate-crew.py

Re-run only when the source photos change.
"""
from pathlib import Path
import json

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT.parent / "world-cup-sweepstake" / "data" / "owners"
OUT = ROOT / "games" / "waffle-wednesday" / "crew-sprites.js"

CREW = ["marriott", "pitt", "nash", "marco", "james", "groves"]
SIZE = 28
COLORS = 16


def make_sprite(path: Path) -> dict:
    img = Image.open(path).convert("RGB")
    w, h = img.size
    side = min(w, h)
    left, top = (w - side) // 2, (h - side) // 2
    img = img.crop((left, top, left + side, top + side))
    img = img.resize((SIZE, SIZE), Image.NEAREST)
    img = img.quantize(colors=COLORS, method=Image.Quantize.MEDIANCUT)

    raw = img.getpalette()[: COLORS * 3]
    palette = ["#%02x%02x%02x" % (raw[i], raw[i + 1], raw[i + 2]) for i in range(0, len(raw), 3)]
    # trim palette to the highest index actually used
    idx = list(img.getdata())
    used = max(idx) + 1
    palette = palette[:used]
    pixels = "".join("%x" % v for v in idx)
    return {"w": SIZE, "h": SIZE, "palette": palette, "pixels": pixels}


def main() -> None:
    if not SRC.is_dir():
        raise SystemExit(f"source headshots not found at {SRC}")
    sprites = {name: make_sprite(SRC / f"{name}.jpg") for name in CREW}
    body = ",\n  ".join(f"{k}: {json.dumps(v)}" for k, v in sprites.items())
    OUT.write_text(
        "// GENERATED by scripts/pixelate-crew.py — do not hand-edit.\n"
        "// 28x28 indexed-colour pixel portraits of the Waffle Wednesday crew,\n"
        "// derived from world-cup-sweepstake/data/owners/*.jpg.\n"
        "export const CREW_SPRITES = {\n  " + body + ",\n};\n",
        encoding="utf8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
